name: coghri_audio_dev

services:
  audio_device_manager_service:
    container_name: "eth_audio_device_manager"
    env_file:
      - ./.env
    network_mode: host
    ipc: host
    shm_size: 1gb
    runtime: ${DOCKER_RUNTIME:-runc}
    image: ${BUILT_IMAGE}
    privileged: true
    depends_on:
      - mongodb_service
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.xauth_docker/share/:/tmp/xauth/
      - ./.vscode:/workspace/.vscode
      - ./logs:/workspace/log
      - ../src/audio_stream_manager:/workspace/src/audio_stream_manager
      - ../src/speech_recognition:/workspace/src/speech_recognition
      - ../src/speech_recognition/speech_recognition/weights_pyannote:/root/.cache/torch/pyannote:rw
      - /dev:/dev
            # Cyclone DDS configuration for TiagoPro Ethernet
      - ./cyclone_xmls/${CYCLONE_CONFIG_FILE:-cyclonedds_ethernet.xml}:/etc/cyclonedds.xml:ro
    tty: true
    stdin_open: true
    environment:
      - CYCLONEDDS_URI=file:///etc/cyclonedds.xml
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-2}  
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}   
      - PACKAGE_NAME=audio_stream_manager
      - NVIDIA_VISIBLE_DEVICES=all 
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/xauth/.docker.xauth     
      - HF_TOKEN=${HF_TOKEN}      
      - TORCH_HOME=/root/.cache/torch
      - AI_VENV=/opt/ros_python_env

    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - 'c 180:* rwm'  # 180 is usb
      - 'c 189:* rwm' # 189 is usb_device

    command: >
      bash -c "source /workspace/install/setup.bash && export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp &&
      exec ros2 launch audio_stream_manager audio_stream_manager.launch.py"


  speech_recognition_service:
    container_name: "eth_speech_recognition"
    env_file:
      - ./.env
    network_mode: host
    ipc: host
    shm_size: 1gb
    runtime: ${DOCKER_RUNTIME:-runc}
    image: ${BUILT_IMAGE}
    privileged: true
    depends_on:
      - mongodb_service
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.xauth_docker/share/:/tmp/xauth/
      - ./.vscode:/workspace/.vscode
      - ./logs:/workspace/log
      - ../src/audio_stream_manager:/workspace/src/audio_stream_manager
      - ../src/speech_recognition:/workspace/src/speech_recognition
      - ../src/speech_recognition/speech_recognition/weights_pyannote:/root/.cache/torch/pyannote:rw
      - /dev:/dev
            # Cyclone DDS configuration for TiagoPro Ethernet
      - ./cyclone_xmls/${CYCLONE_CONFIG_FILE:-cyclonedds_ethernet.xml}:/etc/cyclonedds.xml:ro
    tty: true
    stdin_open: true
    environment:
      - CYCLONEDDS_URI=file:///etc/cyclonedds.xml
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-2}  
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}   
      - PACKAGE_NAME=speech_recognition
      - NVIDIA_VISIBLE_DEVICES=all 
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/xauth/.docker.xauth     
      - HF_TOKEN=${HF_TOKEN}
      - TORCH_HOME=/root/.cache/torch
      - AI_VENV=/opt/ros_python_env

    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - 'c 180:* rwm'  # 180 is usb
      - 'c 189:* rwm' # 189 is usb_device
    
    # Enable/disable components via launch file arguments:
    # ros2 launch speech_recognition speech_recognition.launch.py enable_vad:=false enable_diarization:=false enable_asr:=false enable_wake_word:=false
    command: >
      bash -c "source /workspace/install/setup.bash &&  export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp &&
      exec ros2 launch speech_recognition speech_recognition.launch.py"

    stop_signal: SIGINT
    stop_grace_period: 30s

  mongodb_service:
    image: mongo:7
    container_name: "mongodb"
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eurecat
      - MONGO_INITDB_ROOT_PASSWORD=cerdanyola
    stop_signal: SIGTERM
    stop_grace_period: 60s
    #if any change in env vars, need to delete volume coghri_speakers_mongodb_data to reinit DB
    #docker compose down -v

  mongo_express:
    image: mongo-express:latest
    container_name: "mongo-express"
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - mongodb_service
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=eurecat
      - ME_CONFIG_MONGODB_ADMINPASSWORD=cerdanyola
      - ME_CONFIG_MONGODB_SERVER=mongodb_service
      - ME_CONFIG_MONGODB_URL=mongodb://eurecat:cerdanyola@mongodb_service:27017/?authSource=admin


volumes:
  mongodb_data:
    name: coghri_speakers_mongodb_data
    driver: local
    