name: coghri_audio_processing

services:
  audio_device_manager_service:
    container_name: "audio_device_manager"
    network_mode: host
    ipc: host
    shm_size: 1gb
    runtime: ${DOCKER_RUNTIME:-runc}
    image: ${BUILT_IMAGE}
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.xauth_docker/share/:/tmp/xauth/
      - ./.vscode:/workspace/.vscode
      - ../src/audio_stream_manager:/workspace/src/audio_stream_manager
      - ../src/speech_recognition:/workspace/src/speech_recognition
      - ../src/speech_recognition/speech_recognition/weights_pyannote:/root/.cache/torch/pyannote:rw
      - /dev:/dev
    tty: true
    stdin_open: true
    environment:
      # - RMW_FASTRTPS_PUBLICATION_MODE=ASYNCHRONOUS
      # - FASTDDS_BUILTIN_TRANSPORTS=LARGE_DATA
      # - RMW_IMPLEMENTATION=rmw_fastrtps_cpp    
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}    
      - NVIDIA_VISIBLE_DEVICES=all 
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/xauth/.docker.xauth     
      - HF_TOKEN=${HF_TOKEN}      
      - TORCH_HOME=/root/.cache/torch

    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - 'c 180:* rwm'  # 180 is usb
      - 'c 189:* rwm' # 189 is usb_device

    command: bash -c "source /workspace/install/setup.bash && ros2 launch audio_stream_manager audio_stream_manager.launch.py"

  speech_recognition_service:
    container_name: "speech_recognition"
    network_mode: host
    ipc: host
    shm_size: 1gb
    runtime: ${DOCKER_RUNTIME:-runc}
    image: ${BUILT_IMAGE}
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.xauth_docker/share/:/tmp/xauth/
      - ./.vscode:/workspace/.vscode
      - ../src/audio_stream_manager:/workspace/src/audio_stream_manager
      - ../src/speech_recognition:/workspace/src/speech_recognition
      - ../src/speech_recognition/speech_recognition/weights_pyannote:/root/.cache/torch/pyannote:rw
      - /dev:/dev
    tty: true
    stdin_open: true
    environment:
      # - RMW_FASTRTPS_PUBLICATION_MODE=ASYNCHRONOUS
      # - FASTDDS_BUILTIN_TRANSPORTS=LARGE_DATA
      # - RMW_IMPLEMENTATION=rmw_fastrtps_cpp    
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}    
      - NVIDIA_VISIBLE_DEVICES=all 
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/xauth/.docker.xauth     
      - HF_TOKEN=${HF_TOKEN}      
      - TORCH_HOME=/root/.cache/torch

    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - 'c 180:* rwm'  # 180 is usb
      - 'c 189:* rwm' # 189 is usb_device

    
    # Enable/disable components via launch file arguments:
    # ros2 launch speech_recognition speech_recognition.launch.py enable_vad:=false enable_diarization:=false enable_asr:=false
    command: bash -c "source /workspace/install/setup.bash && ros2 launch speech_recognition speech_recognition.launch.py"
