flowchart TD
    A[Subscription to topic: <b>/audio_and_device_info</b>] --> B[Add audio data to Buffer]
    B --> C{Buffer has 2s <br> of audio data?}
    C -->|Yes| E[Extract 2s window<br/>from buffer]
    C -->|No| D{Buffer > 2s?}
    D -->|No| B
    D -->|Yes| L[Move the sliding window<br/>by 0.5s]
    L --> E
    E --> I[OpenWakeWord model:<br/> <b>hey_jana<b/>]
    I --> J[Compute Wake Word probability]
    J -->|probability| K[Publish <b>/wake_word </b> topic: <br> std_msgs/Header header <br> float32 wake_word_probability]
    
    style A fill:#FFA500
    style B fill:#FFA500
    style K fill:#FFA500